"""add post.body_html

Revision ID: 1ece2b18b6d3
Revises: c23a4036bbd0
Create Date: 2016-06-16 21:02:45.047833

"""

# revision identifiers, used by Alembic.
revision = '1ece2b18b6d3'
down_revision = 'c23a4036bbd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
