"""add users.confirmed

Revision ID: bea776202b94
Revises: None
Create Date: 2016-05-03 20:57:58.425182

"""

# revision identifiers, used by Alembic.
revision = 'bea776202b94'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
